# -*- mode: ruby -*-
# Minimal Brewfile
#
# Pre-configuration for brew sources
tap 'caskroom/cask'
tap 'homebrew/bundle'
tap 'homebrew/core'
tap 'homebrew/dupes'

# Couple of mandatory applications
brew 'autoconf'
brew 'autojump'
brew 'readline'
brew 'bash'
brew 'bash-completion'
brew 'boost', args: ['with-mpi', 'without-single']
brew 'cmake'
brew 'coreutils'
brew 'dsh'
brew 'figlet'
brew 'gdbm'
brew 'git'
brew 'git-crypt'
brew 'git-extras'
brew 'git-flow'
brew 'htop'
brew 'imapfilter'
brew 'jpegoptim'
brew 'libyaml'
brew 'lua'
brew 'mr'
brew 'ninja'
brew 'nmap'
brew 'offlineimap'
brew 'optipng'
brew 'openssl'
brew 'perl'
brew 'sqlite'
brew 'packer'
brew 'pandoc'
brew 'parallel'
brew 'python'
brew 'ruby'
brew 'stow'
brew 'subversion'
brew 'task'
brew 'terminal-notifier'
brew 'tig'
brew 'vim'
brew 'watch'
# more recent rsync
brew 'homebrew/dupes/rsync'

# Mac GUIs Apps
cask '1password'
cask 'alfred'
cask 'calibre'
cask 'dropbox'
cask 'mactex'
cask 'the-unarchiver'
cask 'vagrant'
cask 'vagrant-manager'
cask 'virtualbox'
cask 'yujitach-menumeters'

# Mac Store Apps
mas 'Tweetbot', id: 557168941
mas 'Slack', id: 803453959
mas 'Pages', id: 409201541
mas 'Numbers', id: 409203825
mas 'Keynote', id: 409183694
